### ISSUE TITLE
E: Package 'python' has no installation candidate on Linux Mint 21.

### ISSUE THREAD

**Issue by Pineconium** [lordmilko/i686-elf-tools#28]
Every time I use the i686-elf-tools.sh script, the terminal keeps giving me this error: `E: Package 'python' has no installation candidate`. I made sure I altered my `sources.list `file so what is the issue?

**Comment by lordmilko** [comment]
It is generally recommended to use i686-elf-tools on Ubuntu.

The issue you are experiencing is most likely a result of the fact the python package is now called "python3" instead. You can see there is a hack in the script to install differently named packages when your distro is Ubuntu. Since you're using Linux Mint, `lsb_release -a` would likely return something else

https://github.com/lordmilko/i686-elf-tools/blob/0aed5288bea1825970f796cd2e5580fdbbe3e01d/i686-elf-tools.sh#L142-L146

A proper solution to this would likely involve somehow querying apt whether a `python` or `python3` package is available, and installing the correct one. I'm not super sure how to do that however, and haven't spent the time to investigate this yet.

You can work around this by either hacking the script to match `lsb_release -a` against a string that gets returned on your system, or use the Docker version instead (which has all required prerequisites installed already)

**Comment by NotYourFox** [comment]
### Important note: 
I haven't yet tested whatever I provided on distros other than Mint nor in Docker, so I leave it here for now just as a suggestion and a possible workaround for the issue. I am **not** certain that the exact code below will not break things in some specific or general occasion.

### Suggestion:
I believe a "good enough" solution is to check /etc/os-release for "ubuntu" if lsb_release fails.
```bash
if [[ $(lsb_release -a) =~ .*"Ubuntu".*$ || $(cat /etc/os-release) =~ .*(U|u)buntu.*$ ]]; then
    pkgList+=(python3 python-is-python3)
else
    pkgList+=(python)
fi
```

It is also possible to query apt as you suggested using
```bash
apt-cache search --names-only ^python$
```
This will return nothing if "python" is not present in package cache. Therefore,
```bash
if [[ -n $(apt-cache search --names-only ^python$) ]]; then
    ...
fi
```
or
```bash
if [[ $(apt-cache search --names-only ^python$ | wc -m) -gt 0 ]]; then
    ...
fi
```
might do the trick.

**Comment by lordmilko** [comment]
Thanks @NotYourFox,

I don't currently have the bandwidth to test this, but it seems like this is becoming a not too uncommon issue, so I have updated the README to explicitly direct people to this issue as part of the getting started steps

**Comment by sasdallas** [comment]
@NotYourFox @lordmilko Opened a PR of #32 with a goal to detect this. If you ever get a chance, you could try that.

**Comment by lordmilko** [comment]
This issue should now be resolved. Thanks @NotYourFox for your proposed solutions, and thanks @sasdallas for submitting and testing a PR with these changes
