### ISSUE TITLE
Uninstall feature

### ISSUE THREAD

**Issue by ketgo** [lordmilko/i686-elf-tools#4]
Hi, 

Is it possible to add uninstall feature to the script?

Thanks

**Comment by lordmilko** [comment]
Hi @ketgo,

What is it that you want to uninstall exactly? The build script installs a whole host of dependencies required for using the build tools, before eventually placing the final product in `~/build-i686-elf`. To remove all the build files you can simply do `rm -rf ~/build-i686-elf`.

If you want to uninstall all the stuff that had to be installed in order to do the build, that becomes a lot more trickier; we would then need to keep track of what was already installed on your system prior to running the script so we don't then accidentally uninstall something important used by another application on your system. Such a feature is completely outside the scope of this project; if you don't want to install a bunch of developer tools on your primary machine, I would advise using a virtual machine instead.

**Comment by ketgo** [comment]
Got it, I was able to remove the builds but wanted to also remove the other packages needed for the build. I guess that can be achieved by using a docker image for build. Thx!

**Comment by lordmilko** [comment]
Hi @ketgo,

After reading your response it occurred to me that this project really should include a Docker version!

As such I have made several enhancements to the build script including allowing specifying the product versions to build as commandline arguments and have introduced an [official](https://github.com/lordmilko/i686-elf-tools#docker) i686-elf-tools docker image. This now **greatly** reduces the amount of time it takes to use the build script, eliminating the need to
* Setup a VM
* Install Debian/Ubuntu
* Install all the prerequisites, and
* Configure MXE

Thanks for the idea!

Regards,
lordmilko
