### ISSUE TITLE
i386-elf toolchain on macos?

### ISSUE THREAD

**Issue by Tockra** [lordmilko/i686-elf-tools#7]
Hey,

why does the macos part in your readme just telling stuff about installing i386-elf toolchain ?

T

**Comment by lordmilko** [comment]
Hi @Tockra,

When I was initially trying to compile an i686-elf compiler for my operating system, I discovered that there was already a ready to go i386-elf version available for Mac OS on brew which just worked without any of the pain I had to go through in order to get the compilation for Linux and Windows working.

Presumably that old brew recipe should work; otherwise potentially you can just try compiling the Linux version on your Mac and maybe it will work; the primary goal of this project is to produce a statically linked i686-elf toolchain for Windows; the fact that producing for Windows requires also producing for Linux is just a side benefit; if these instructions also work for Mac, that's great, otherwise directly supporting Mac OS is outside the scope of this project

Regards,
lordmilko
