### ISSUE TITLE
Failed to build with error "configure: error: C compiler cannot create executables"

### ISSUE THREAD

**Issue by AAM1075** [lordmilko/i686-elf-tools#9]
Hello, I am trying to compile FrOS from https://github.com/FRosner/FrOS, and I need to install this script. However, I keep getting the error message "configure: error: C compiler cannot create executables". I am running this script under wsl.

**Comment by lordmilko** [comment]
Hi @xxxMEMESCOEPxxx,

Are you trying to *create* an i686-elf-tools toolchain for your operating system *first*, or are you using the [pre-compiled Linux binary](https://github.com/lordmilko/i686-elf-tools/releases) under WSL?

In addition, are you able to advise which distro you're using under WSL?

**Comment by AAM1075** [comment]
I am using the precompiled binary under wsl, and I am running ubuntu 18.04 LTS under wsl

**Comment by lordmilko** [comment]
Hi @xxxMEMESCOEPxxx,

I tried running the *i686-elf-tools-linux* version of GCC on WSL with Ubuntu 18.04 LTS and I get an "Exec format error", which I believe is because this is a 32-bit executable and WSL requires the use of 64-bit executables. When I try and run the *x86_64-elf-tools-linux* version of GCC the executable does appear to work, so potentially if you copy the contents of the x86_64 zip to under `/usr/local` you can try and update FrOS' Makefile and compile the OS using that.

From reading FrOS' README and Makefile, it seems to me that this project is not actually using any utilities produced by *lordmilko/i686-elf-tools* at all; the author of this project uses macOS, and as such is using the existing *i383-elf-gcc* package that exists on brew, rather than the *i686-elf-gcc* executable that this project would produce. As such, unless you're using the same third party version of `i386-elf-gcc` the author uses, you'll need to update their `Makefile` to point to another GCC executable, which may or may not even work with the FrOS project

**Comment by AAM1075** [comment]
Ok, thanks for the help!
